### ISSUE TITLE
puppet-jira -- Upgrade howto & addons management questions 

### ISSUE THREAD

**Issue by fredfokan** [voxpupuli/puppet-jira#102]
Hello,

I'm a new user of this Puppet-JIRA module.
Making a quick overview of this module, find below my question about it : 
- How do you proceed with all addons contained in JIRA.
- How do you proceed for any upgrade from one existing JIRA instance not managed by Puppet to a new one managed by puppet.
- How do you manage further Jira upgrade.

Thanks by advance for any feedback on above point !

Fred

**Comment by oranenj** [comment]
This issue is a bit old, and I'm not sure if the questions here are something that directly relate to this Puppet module.

But in summary:

- This module doesn't concern itself with JIRA addons, they're out-of-scope.
- Taking over "old" installations with Puppet is generally something you need to plan on a case-by-case basis.
- Once you have JIRA managed by Puppet, upgrades are pretty simple.
