### ISSUE TITLE
CentOS 6 support?

### ISSUE THREAD

**Issue by AnthonyMastrean** [voxpupuli/puppet-jira#167]
Maybe I'm missing something...

CentOS 6 ships with Ruby 1.8.7 and no better version in the package repository. Puppet uses the system Ruby. You can't update Ruby using, say RVM, before running `class { 'jira': }` because Puppet is still running under the system Ruby.

How do you drop support for Ruby 1.8.7 and claim to support CentOS 6?

Let's say I don't control my system image (corporate private cloud) and I don't want to interactively upgrade Ruby or run a separate manifest before running my Jira manifest.

### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.7
- Ruby: 1.8.7
- Distribution: CentOS 6
- Module version: (any)

**Comment by alexjfisher** [comment]
All Vox Pupuli modules have finished supporting ruby 1.8.  Ordinarily I'd say EL6 support is still claimed because puppet 4 is installable and ships with its own ruby 2.1 (IIRC).  This particular module doesn't claim to be puppet 4 compatible though...

That said, you should be OK.  This module doesn't have any functions, facts or native types/providers, so the fact that it isn't tested/supported on ruby 1.8 shouldn't affect you - I don't think.  There are templates, but I can't immediately see any recent changes that would break on ruby 1.8.

**Comment by AnthonyMastrean** [comment]
Oh, see I'm so far behind, I didn't realize Puppet 4 shipped with it's own Ruby. That might do the trick, although I'll have to update all my manifests.

I thought I saw some errors due to Ruby 2 hashes, but that might have been one of the dependencies.

**Comment by alexjfisher** [comment]
@AnthonyMastrean No worries.  I think puppet 3 is End Of Life at the end of this year.  One way to start your migration might be to enable puppet 3's future parser option and see what that throws up.

**Comment by AnthonyMastrean** [comment]
Yeaaah. I'm screwed :)
