### ISSUE TITLE
JVM_REQUIRED_ARGS is missing -Dorg.dom4j.factory=com.atlassian.core.xml.InterningDocumentFactory

### ISSUE THREAD

**Issue by mojibake-umd** [voxpupuli/puppet-jira#309]
I do not know when -Dorg.dom4j.factory=com.atlassian.core.xml.InterningDocumentFactory was added to JVM_REQUIRED_ARGS by Atlassian, but it is missing from setenv.sh as it is being delivered by ERB template. 

I was able to get around by setting the following in Hiera.
jira::java_opts: '-XX:InitialCodeCacheSize=32m -XX:ReservedCodeCacheSize=512m -Dorg.dom4j.factory=com.atlassian.core.xml.InterningDocumentFactory'

-XX:InitialCodeCacheSize=32m -XX:ReservedCodeCacheSize=512m is documented in #308

**Comment by oranenj** [comment]
Fixed in current master
{noformat}
<%- if scope.call_function('versioncmp', [@version, '8.11.0']) > 0 -%>
JVM_REQUIRED_ARGS='-Djava.awt.headless=true -Datlassian.standalone=JIRA -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true -Dmail.mime.decodeparameters=true -Dorg.dom4j.factory=com.atlassian.core.xml.InterningDocumentFactory'
<% else -%>
{noformat}
