### ISSUE TITLE
JIRA will not start if the installation directory mode is missing o+x

### ISSUE THREAD

**Issue by koraz0815** [voxpupuli/puppet-jira#377]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: v7.6.1
- Ruby: 2.0.0
- Distribution: CentOS 7.9
- Module version: 5.0.1

## How to reproduce (e.g Puppet code you use)
I have set the parameter $installdir and the module change the permissions to root not to user jira.

## What are you seeing
`$installdir => /opt/atlassian-jira`
after puppet agent was running on the machine i see that User jira have no permissions to execute the startup-script in this folder
```
root@jira:/opt# ll /opt/
total 0
drwxr-xr-x.  7 root root 146 28. Apr 10:35 .
dr-xr-xr-x. 20 root root 257 28. Apr 10:34 ..
drwxr-x---.  3 root root  94 28. Apr 10:35 atlassian-jira
```
systemd cant start jira and I see the following output in the `journalctl -xe`
```
Failed at step EXEC spawning /opt/atlassian-jira/atlassian-jira-software-8.13.6-standalone/bin/start-jira.sh: Permission denied
```
Maybe I think that this https://github.com/voxpupuli/puppet-jira/blob/master/manifests/install.pp#L45 is not working

**Comment by oranenj** [comment]
The problem seems to be the installdir's permissions: you don't have `o+x`, so JIRA can't enter any subdirectories.

The ownership was changed to root because this solved a dependency issue if you put the data directory under the installation directory. The JIRA application should never need to write into the directory where the binaries reside; that's what the data directory is for, but it does need to read from it.

The module should probably enforce that the installation directory has `0755` mode

**Comment by oranenj** [comment]
@koraz0815 I created a PR to make sure the installation directory has a sane mode. In the meantime, just `chmod 0755 /opt/atlassian-jira` and it should start again.
